/* Elencos-titulares padrão por sigla (Gauchão Série A2).
   Usado no auto-preenchimento: ao escolher a sigla de um time na
   escalação, os 11 jogadores são preenchidos a partir daqui (e o nome
   do time também). Edite livremente — são valores iniciais editáveis. */

export const ELENCOS_POR_SIGLA = {
  PEL: [
    { num: '1', nome: 'FERNANDO' },
    { num: '2', nome: 'ALISSON' },
    { num: '3', nome: 'MAICON' },
    { num: '4', nome: 'RODRIGO' },
    { num: '6', nome: 'BRUNO' },
    { num: '8', nome: 'GUSTAVO' },
    { num: '10', nome: 'THIAGO' },
    { num: '11', nome: 'VINICIUS' },
    { num: '7', nome: 'RAFAEL' },
    { num: '9', nome: 'DIEGO' },
    { num: '17', nome: 'LUCAS' },
  ],
  BRA: [
    { num: '1', nome: 'GABRIEL' },
    { num: '2', nome: 'MATHEUS' },
    { num: '3', nome: 'JOAO' },
    { num: '4', nome: 'PEDRO' },
    { num: '6', nome: 'FELIPE' },
    { num: '8', nome: 'RICARDO' },
    { num: '10', nome: 'ANDRÉ' },
    { num: '11', nome: 'MARCOS' },
    { num: '7', nome: 'EDUARDO' },
    { num: '9', nome: 'RENATO' },
    { num: '18', nome: 'CAIO' },
  ],
  VER: [
    { num: '1', nome: 'IGOR' },
    { num: '2', nome: 'CESAR' },
    { num: '3', nome: 'DOUGLAS' },
    { num: '4', nome: 'LEANDRO' },
    { num: '6', nome: 'PAULO' },
    { num: '8', nome: 'JEFERSON' },
    { num: '10', nome: 'DAVI' },
    { num: '11', nome: 'WESLEY' },
    { num: '7', nome: 'EMERSON' },
    { num: '9', nome: 'BRUNO' },
    { num: '19', nome: 'SAMUEL' },
  ],
  PAS: [
    { num: '1', nome: 'MARCELO' },
    { num: '2', nome: 'VICTOR' },
    { num: '3', nome: 'DANIEL' },
    { num: '4', nome: 'ALAN' },
    { num: '6', nome: 'ROBERTO' },
    { num: '8', nome: 'FABIO' },
    { num: '10', nome: 'JONATAS' },
    { num: '11', nome: 'AUGUSTO' },
    { num: '7', nome: 'NICOLAS' },
    { num: '9', nome: 'CLAUDIO' },
    { num: '20', nome: 'EWERTON' },
  ],
  ESP: [
    { num: '1', nome: 'DIOGO' },
    { num: '2', nome: 'RAFAEL' },
    { num: '3', nome: 'VINICIUS' },
    { num: '4', nome: 'GUSTAVO' },
    { num: '6', nome: 'LUCAS' },
    { num: '8', nome: 'MATHEUS' },
    { num: '10', nome: 'FERNANDO' },
    { num: '11', nome: 'PEDRO' },
    { num: '7', nome: 'EMERSON' },
    { num: '9', nome: 'GABRIEL' },
    { num: '21', nome: 'RODRIGO' },
  ],
  AIM: [
    { num: '1', nome: 'JUNIOR' },
    { num: '2', nome: 'MURILO' },
    { num: '3', nome: 'JEFERSON' },
    { num: '4', nome: 'THIAGO' },
    { num: '6', nome: 'ANDERSON' },
    { num: '8', nome: 'CRISTIAN' },
    { num: '10', nome: 'LEONARDO' },
    { num: '11', nome: 'MAICON' },
    { num: '7', nome: 'DIOGO' },
    { num: '9', nome: 'FABRICIO' },
    { num: '22', nome: 'HENRIQUE' },
  ],
  SCR: [
    { num: '1', nome: 'RAMON' },
    { num: '2', nome: 'ERICK' },
    { num: '3', nome: 'DANILO' },
    { num: '4', nome: 'IAN' },
    { num: '6', nome: 'WELLINGTON' },
    { num: '8', nome: 'THALES' },
    { num: '10', nome: 'YAGO' },
    { num: '11', nome: 'BRENO' },
    { num: '7', nome: 'MATHEUS' },
    { num: '9', nome: 'PABLO' },
    { num: '23', nome: 'RONALDO' },
  ],
  APA: [
    { num: '1', nome: 'AIRTON' },
    { num: '2', nome: 'GABRIEL' },
    { num: '3', nome: 'JONAS' },
    { num: '4', nome: 'TIAGO' },
    { num: '6', nome: 'FELIPE' },
    { num: '8', nome: 'DOUGLAS' },
    { num: '10', nome: 'RAFAEL' },
    { num: '11', nome: 'JUNIOR' },
    { num: '7', nome: 'LEO' },
    { num: '9', nome: 'MAURICIO' },
    { num: '24', nome: 'VITOR' },
  ],
  UFR: [
    { num: '1', nome: 'GUILHERM' },
    { num: '2', nome: 'ARTHUR' },
    { num: '3', nome: 'PHILLIP' },
    { num: '4', nome: 'MAXWELL' },
    { num: '6', nome: 'LUAN' },
    { num: '8', nome: 'ERICK' },
    { num: '10', nome: 'FELIPE' },
    { num: '11', nome: 'KAUE' },
    { num: '7', nome: 'NATHAN' },
    { num: '9', nome: 'BRENO' },
    { num: '25', nome: 'DAVI' },
  ],
  GAU: [
    { num: '1', nome: 'RONI' },
    { num: '2', nome: 'IGOR' },
    { num: '3', nome: 'NICOLAS' },
    { num: '4', nome: 'MATEUS' },
    { num: '6', nome: 'JOAO' },
    { num: '8', nome: 'PEDRO' },
    { num: '10', nome: 'GABRIEL' },
    { num: '11', nome: 'VITOR' },
    { num: '7', nome: 'LUCAS' },
    { num: '9', nome: 'MURILO' },
    { num: '26', nome: 'REYNALDO' },
  ],
  BFR: [
    { num: '1', nome: 'EBERSON' },
    { num: '2', nome: 'MATHEUS' },
    { num: '3', nome: 'CAUE' },
    { num: '4', nome: 'WILLIAM' },
    { num: '6', nome: 'ANTHONY' },
    { num: '8', nome: 'BRYAN' },
    { num: '10', nome: 'EDSON' },
    { num: '11', nome: 'GILSON' },
    { num: '7', nome: 'HUDSON' },
    { num: '9', nome: 'JEFERSON' },
    { num: '27', nome: 'KAUAN' },
  ],
  GRA: [
    { num: '1', nome: 'LEANDRO' },
    { num: '2', nome: 'GABRIEL' },
    { num: '3', nome: 'MARCUS' },
    { num: '4', nome: 'VINICIUS' },
    { num: '6', nome: 'WILLIAM' },
    { num: '8', nome: 'RAFAEL' },
    { num: '10', nome: 'DENIS' },
    { num: '11', nome: 'FABIO' },
    { num: '7', nome: 'EVERTON' },
    { num: '9', nome: 'LUAN' },
    { num: '28', nome: 'ADRIANO' },
  ],
  GUA: [
    { num: '1', nome: 'THIAGO' },
    { num: '2', nome: 'GUSTAVO' },
    { num: '3', nome: 'DAVID' },
    { num: '4', nome: 'RAMIRO' },
    { num: '6', nome: 'JONATAN' },
    { num: '8', nome: 'WELLINGTON' },
    { num: '10', nome: 'RONALDO' },
    { num: '11', nome: 'CRISTIAN' },
    { num: '7', nome: 'HENRIQUE' },
    { num: '9', nome: 'PABLO' },
    { num: '29', nome: 'SANDRO' },
  ],
  BAG: [
    { num: '1', nome: 'JEAN' },
    { num: '2', nome: 'RICARDO' },
    { num: '3', nome: 'CLAUDIO' },
    { num: '4', nome: 'DOUGLAS' },
    { num: '6', nome: 'ERICO' },
    { num: '8', nome: 'FLAVIO' },
    { num: '10', nome: 'MAICON' },
    { num: '11', nome: 'DIEGO' },
    { num: '7', nome: 'SIDNEI' },
    { num: '9', nome: 'RAFAEL' },
    { num: '30', nome: 'VANDER' },
  ],
  GLO: [
    { num: '1', nome: 'JULIANO' },
    { num: '2', nome: 'MARCELO' },
    { num: '3', nome: 'TALES' },
    { num: '4', nome: 'ANDERSON' },
    { num: '6', nome: 'GUI' },
    { num: '8', nome: 'RAMON' },
    { num: '10', nome: 'LEO' },
    { num: '11', nome: 'FELIPE' },
    { num: '7', nome: 'WESLEY' },
    { num: '9', nome: 'GILMAR' },
    { num: '31', nome: 'EDUARDO' },
  ],
  LAJ: [
    { num: '1', nome: 'RONY' },
    { num: '2', nome: 'MAICON' },
    { num: '3', nome: 'DAVI' },
    { num: '4', nome: 'THALES' },
    { num: '6', nome: 'MATEUS' },
    { num: '8', nome: 'PEDRO' },
    { num: '10', nome: 'JOAO' },
    { num: '11', nome: 'MARCOS' },
    { num: '7', nome: 'VITOR' },
    { num: '9', nome: 'GABRIEL' },
    { num: '32', nome: 'RODRIGO' },
  ],
}

export function elencoDaSigla(sigla) {
  const lista = ELENCOS_POR_SIGLA[String(sigla || '').toUpperCase()]
  if (!lista || !lista.length) return null
  return lista.map((j) => ({
    num: String(j.num || ''),
    nome: String(j.nome || '').toUpperCase(),
    cartoes: { amarelo: 0, vermelho: 0 },
    gols: 0,
  }))
}

/* Nome completo por sigla (usado no auto-preenchimento) */
export const NOMES_POR_SIGLA = {
  PEL: 'PELOTAS',
  BRA: 'BRASIL',
  VER: 'VERANÓPOLIS',
  PAS: 'PASSO FUNDO',
  ESP: 'ESPORTIVO',
  AIM: 'AIMORÉ',
  SCR: 'SANTA CRUZ',
  APA: 'APAFUT',
  UFR: 'UNIÃO FREDERIQUENSE',
  GAU: 'GAÚCHO',
  BFR: 'BRASIL DE FARROUPILHA',
  GRA: 'GRAMADENSE',
  GUA: 'GUARANI VA',
  BAG: 'BAGÉ',
  GLO: 'GLORIA',
  LAJ: 'LAJEADENSE',
}

export function nomeDaSigla(sigla) {
  return NOMES_POR_SIGLA[String(sigla || '').toUpperCase()] || ''
}
